export const sepsisData = [
  {
    Study: "Smith et al.",
    Year: 2021,
    Population: "Septic shock",
    N: 240,
    SOFA: 9,
    Lactate: 4.2,
    "Antibiotic Timing": 2.1,
    "28-day Mortality": 32,
    Source: "Page 4, Table 2",
    Confidence: "91%",
  },
  {
    Study: "Garcia et al.",
    Year: 2020,
    Population: "Severe sepsis",
    N: 310,
    SOFA: 8,
    Lactate: 3.6,
    "Antibiotic Timing": 1.4,
    "28-day Mortality": 25,
    Source: "Page 6, Results",
    Confidence: "86%",
  },
  {
    Study: "Chen et al.",
    Year: 2019,
    Population: "ICU sepsis",
    N: 180,
    SOFA: 11,
    Lactate: 5.1,
    "Antibiotic Timing": 3.2,
    "28-day Mortality": 41,
    Source: "Page 5, Table 3",
    Confidence: "93%",
  },
  {
    Study: "Patel et al.",
    Year: 2022,
    Population: "Septic shock",
    N: 275,
    SOFA: 10,
    Lactate: 4.7,
    "Antibiotic Timing": 2.6,
    "28-day Mortality": 38,
    Source: "Page 7, Table 1",
    Confidence: "89%",
  },
  {
    Study: "Johnson et al.",
    Year: 2018,
    Population: "Severe sepsis",
    N: 200,
    SOFA: 7,
    Lactate: 3.3,
    "Antibiotic Timing": 1.2,
    "28-day Mortality": 22,
    Source: "Page 3, Results",
    Confidence: "84%",
  },
];